### ISSUE TITLE
CMS Erkennung 

### ISSUE THREAD

**Issue by xwolfde** [N3LL4-01/Catcher#2]
Hi, 
Ich kann leider auf x nicht kommentieren, daher hier:

die CMS Erkennung in der utils ist noch etwas rudimentär. Falls du hierzu noch mehr (und nicht offensive) Identifikationsmöglichkeiten brauchst, kannst du hier in einem Scanner-Projekt von mir einige finden, sortiert nach CMS: 
https://github.com/RRZE-Webteam/RRZE-Website-Scanner/tree/main/includes%2FCMS

Ist zwar dort PHP, aber der Übertrag in py sollte kein Problem sein. 

Ciao 
Wolfgang

**Comment by N3LL4-01** [comment]
Danke dir für deinen tipp, hatte auch vor gehabt es weiter auszubauen, dann schaue ich mir deine als Inspiration an. Kann dich dann auch gern erwähnen. Man liest sich Nella  
Am Samstag, 27. Juli 2024 um 13:45, Wolfgang Wiese ***@***.***&gt; schrieb:  Hi,

Ich kann leider auf x nicht kommentieren, daher hier:
die CMS Erkennung in der utils ist noch etwas rudimentär. Falls du hierzu noch mehr (und nicht offensive) Identifikationsmöglichkeiten brauchst, kannst du hier in einem Scanner-Projekt von mir einige finden, sortiert nach CMS:

https://github.com/RRZE-Webteam/RRZE-Website-Scanner/tree/main/includes%2FCMS
Ist zwar dort PHP, aber der Übertrag in py sollte kein Problem sein.
Ciao

Wolfgang
